### ISSUE TITLE
Getting error when trying to compile

### ISSUE THREAD

**Issue by Anahkiasen** [jtangelder/sass-loader#115]
Getting this error when trying to compile, not sure why:

```
ERROR in ./~/css-loader!./~/sass-loader!./assets/css/styles.scss
Module build failed: TypeError: Cannot read property 'sections' of null
    at new SourceMapConsumer (/Users/anahkiasen/Sites/webpack/node_modules/postcss/node_modules/source-map/lib/source-map/source-map-consumer.js:23:21)
    at PreviousMap.consumer (/Users/anahkiasen/Sites/webpack/node_modules/postcss/lib/previous-map.js:37:34)
    at new Input (/Users/anahkiasen/Sites/webpack/node_modules/postcss/lib/input.js:42:28)
    at Object.parse [as default] (/Users/anahkiasen/Sites/webpack/node_modules/postcss/lib/parse.js:17:17)
    at new LazyResult (/Users/anahkiasen/Sites/webpack/node_modules/postcss/lib/lazy-result.js:54:42)
    at Processor.process (/Users/anahkiasen/Sites/webpack/node_modules/postcss/lib/processor.js:30:16)
    at processCss (/Users/anahkiasen/Sites/webpack/node_modules/css-loader/lib/processCss.js:168:24)
    at Object.module.exports (/Users/anahkiasen/Sites/webpack/node_modules/css-loader/lib/loader.js:21:15)
 @ ./assets/js/app.js 1:0-41
```

**js/app.js**
```js
require('!css!sass!./../css/styles.scss');
```

**css/styles.scss**
```scss
$color: red;

body {
  background: $color;
}
```

```
$ node --version && npm --version
v0.12.5
3.0.0
```

**Comment by pcvandamcb** [comment]
I get the exact same error...

v0.12.3
2.9.1

**Comment by namxam** [comment]
Me too. Any idea how to fix it?

**Comment by pcvandamcb** [comment]
I've been testing around and downgrading css-loader to a version prior to 0.15 (0.14.5) fixed it for me.

npm i css-loader@0.14

**Comment by hendrikswan** [comment]
@pcvandamcb that worked for me too!

**Comment by vectart** [comment]
Related issue https://github.com/webpack/css-loader/issues/84

**Comment by SunPeter** [comment]
@hendrikswan Me too.

**Comment by nathanjsharpe** [comment]
It's probably not ideal, but appending `?sourceMap` to `sass` in the loader at least fixes the error. I'm on css-loader 15.1.

```
        {
            test: /\.scss$/,
            include: path.join(__dirname, 'src', 'scss'),
            loader: "style!css!sass?sourceMap"
        }
```

**Comment by lijunle** [comment]
@nathanjsharpe 's [solution](#issuecomment-119789198) resolve this problem.

**Comment by vectart** [comment]
CSS-loader v0.15.3 fixes **Ignore null source maps** by https://github.com/webpack/css-loader/pull/99

**Comment by jhnns** [comment]
Close?
