### ISSUE TITLE
`//` comments result in `Unknown word`

### ISSUE THREAD

**Issue by geekingfrog** [jtangelder/sass-loader#171]
If a file has a comment with `//`, the loader will fail with the error:

```
    Module build failed: CssSyntaxError: /Users/Greg1/projects/opensignal-toolchain/node_modules/scss-lint-loader/index.js!/Users/Greg1/projects/opensignal-toolchain/lib/css/index.scss:2:4: Unknown word
        at Input.error (/Users/Greg1/projects/opensignal-toolchain/node_modules/css-loader/node_modules/postcss/lib/input.js:61:21)
        at Parser.unknownDecl (/Users/Greg1/projects/opensignal-toolchain/node_modules/css-loader/node_modules/postcss/lib/parser.js:470:26)
        at Parser.decl (/Users/Greg1/projects/opensignal-toolchain/node_modules/css-loader/node_modules/postcss/lib/parser.js:227:22)
        at Parser.word (/Users/Greg1/projects/opensignal-toolchain/node_modules/css-loader/node_modules/postcss/lib/parser.js:135:30)
        at Parser.loop (/Users/Greg1/projects/opensignal-toolchain/node_modules/css-loader/node_modules/postcss/lib/parser.js:60:26)
        at parse (/Users/Greg1/projects/opensignal-toolchain/node_modules/css-loader/node_modules/postcss/lib/parse.js:25:12)
        at new LazyResult (/Users/Greg1/projects/opensignal-toolchain/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:57:24)
        at Processor.process (/Users/Greg1/projects/opensignal-toolchain/node_modules/css-loader/node_modules/postcss/lib/processor.js:36:16)
        at processCss (/Users/Greg1/projects/opensignal-toolchain/node_modules/css-loader/lib/processCss.js:165:11)
        at Object.module.exports (/Users/Greg1/projects/opensignal-toolchain/node_modules/css-loader/lib/loader.js:22:2)
```

**Comment by jhnns** [comment]
Could you please create a minimal example that demonstrates the problem? I'm using these comments all the time and there are no problems.

**Comment by ajsharp** [comment]
I'm seeing this issue as well.

**Comment by jhnns** [comment]
I'd appreciate an example :grin:. Furthermore, it's likely not an issue with sass-loader itself, but with node-sass or libsass.

**Comment by djfm** [comment]
Same issue here!

**Comment by jhnns** [comment]
We're using these comments [in our tests](https://github.com/jtangelder/sass-loader/blob/fee3593e5f8658b4afd1f01bc8308718ca0fd439/test/scss/imports.scss#L5), so it's not a generic issue. Please provide examples.

**Comment by djfm** [comment]
@jhnns false alarm, sorry!

We were mis-using the `ExtractTextPlugin` plugin and `sass-loader` wasn't even invoked, hence the parse error when `css-loader` tried to parse the raw sass.

For reference, the corrected version of the loader that we now use is [as follows](https://github.com/PrestaShop/PrestaShop/blob/feat/classic/themes/classic/_dev/webpack.config.js#L40):

```javascript
{
        test: /\.scss$/,
        loader: ExtractTextPlugin.extract(
                "style",
                "css?sourceMap!postcss!sass?sourceMap"
        )
}
```

Maybe some of the other reported errors are also due to a misconfiguration of something other than `sass-loader` itself.

**Comment by jhnns** [comment]
@djfm thanks for informing me
@geekingfrog @ajsharp does that solve your issue?

**Comment by geekingfrog** [comment]
I'm not using webpack anymore so I can't confirm but it's likely that would fix it.

**Comment by ianwalter** [comment]
I get the error:
```
ERROR in ./boyscout-core.scss
/Users/ian/boyscout/boyscout-core.scss:1:1: Unknown word
// Layout
^
@import 'modules/layout/position';

ERROR in ./boyscout-core.scss
Module build failed: TypeError: Cannot read property 'trim' of undefined
    at Object.module.exports (/Users/ian/boyscout/node_modules/sass-loader/index.js:211:16)
 @ multi main
Child extract-text-webpack-plugin:
```
Here is the webpack config:
https://github.com/ianwalter/boyscout/blob/v0.4.0/tools/webpack.config.js
And the .scss file is one directory up in `boyscout-core.scss`.
I'm sure it's my fault, but it's strange that it compiles fine if I remove the comments.

**Comment by jhnns** [comment]
In your configuration, the postcss-loader is executed *before* the sass-loader. Maybe PostCSS isn't able to parse SASS? :grin:

**Comment by ianwalter** [comment]
Ah, I didn't realize it executes in reverse of the order in which its specified, thanks!

**Comment by i4got10** [comment]
I had a similar problem - error with processing css. Fix it with @djfm config. 

Config from sass-loader example that doesn't work for me.

```
module.exports = {
  ...
  module: {
    loaders: [
      {
        test: /\.scss$/,
        loaders: ["style", "css", "sass"]
      }
    ]
  }
};
```

There is a workaround that I used(set loaders at every import)

    import styles from '!style!css!sass!./codemirror.scss';

And finally, right solution

```
module.exports = {
  ...
  module: {
    loaders: [
      {
        test: /\.scss$/,
        loaders: ["style", "css?sourceMap!sass?sourceMap"]
      }
    ]
  }
};
```

**Comment by jhnns** [comment]
Ok, I think we can close this one?

**Comment by windsome** [comment]
@jhnns @i4got10 @djfm 

when I try to use bootstrap-scss, I got this error. missing sass-loader? ref: https://github.com/windsome/rrrsn/blob/master/webpack/webpack.config.prod.js
```
ERROR in ./~/css-loader?sourceMap!./app/styles/assets/stylesheets/_bootstrap.scss
Module build failed: CssSyntaxError: /css-loader!/home/dev/frontend/rrrsn/app/styles/assets/stylesheets/_bootstrap.scss:7:1: Unknown word
    at Input.error (/home/dev/frontend/rrrsn/node_modules/postcss/lib/input.js:61:22)
    at Parser.unknownWord (/home/dev/frontend/rrrsn/node_modules/postcss/lib/parser.js:457:26)
    at Parser.word (/home/dev/frontend/rrrsn/node_modules/postcss/lib/parser.js:174:14)
    at Parser.loop (/home/dev/frontend/rrrsn/node_modules/postcss/lib/parser.js:60:26)
    at parse (/home/dev/frontend/rrrsn/node_modules/postcss/lib/parse.js:26:12)
    at new LazyResult (/home/dev/frontend/rrrsn/node_modules/postcss/lib/lazy-result.js:61:24)
    at Processor.process (/home/dev/frontend/rrrsn/node_modules/postcss/lib/processor.js:34:16)
    at processCss (/home/dev/frontend/rrrsn/node_modules/css-loader/lib/processCss.js:188:11)
    at Object.module.exports (/home/dev/frontend/rrrsn/node_modules/css-loader/lib/loader.js:24:2)
 @ ./~/css-loader?sourceMap!./app/styles/app.scss 4:10-105
```
I've tried the following:
```
{
        test: /\.scss$/,
        loaders: ["style", "css?sourceMap!sass?sourceMap"]
}
```
or
```
{
        test: /\.scss$/,
        loader: ExtractTextPlugin.extract(
                "style",
                "css?sourceMap!postcss!sass?sourceMap"
        )
}
```
But, no use. can you help me?
```
git clone https://github.com/windsome/rrrsn.git
cd rrrsn
npm install
npm run build
```

**Comment by windsome** [comment]
@geekingfrog @ajsharp @ianwalter , how do you solve the problem?

**Comment by jhnns** [comment]
`Header.scss` mixes CSS modules *and* tries to import stuff from Sass. This is not possible. Every import from a CSS file will *not* be compiled with the webpack loader pipeline. You can only import CSS files. Please stick to Sass *or* CSS modules.

**Comment by mkarajohn** [comment]
I think I am having a related issue, maybe someone could help me out? http://stackoverflow.com/questions/40095558/load-specific-component-from-mdl-using-webpack

**Comment by splurtcake** [comment]
Still having this issue. Where am I going wrong?

```
const styleLoaders = [
	'css?sourceMap',
	'postcss?sourceMap',
	'sass?sourceMap'
];

const paths = {
	src: {
		root: path.join(__dirname, 'src/'),
		styles: 'app/assets/sass/',
	},
	dist: {
		styles: 'css/',
	}
};


export var clientConfig = {
	target: 'web',
	entry: {
		'polyfills': './src/polyfills.browser',
		'vendor': './src/vendor',
		'main': './src/client',
		'styles': './src/app/assets/sass/styles.scss'
	},
	output: {
		path: root('dist/client')
	},
	plugins: [
		new ExtractTextPlugin({
			filename: path.join(paths.dist.styles, 'styles.css'),
			disable: false,
			allChunks: true
		})
	],
	module: {
		loaders: [
			{
				test: /\.scss$/,
				include: path.join(paths.src.root, paths.src.styles),
				loader: ExtractTextPlugin.extract(styleLoaders.join('!'))
			},
		]
	}
};
```
