### ISSUE TITLE
Unexpected token

### ISSUE THREAD

**Issue by stigmat4j** [jtangelder/sass-loader#208]
My scss file
```
:local(.styles) {
  position: relative;

  padding: 50px 0;

  .tool {
    text-align: center;
    margin: 30px 0;

    img {
      width: 80%;
    }
  }
}
```

my loader 
```
 {
    test: /\.scss$/,
    loader: 'style!css!sass'
  }
```

and error
```
[1] SyntaxError: /home/max/projects/tradeintelclient/src/components/header.scss: Unexpected token (1:0)
[1] > 1 | :local(.styles) {
[1]     | ^
[1]   2 |   position: relative;
[1]   3 | 
[1]   4 |   padding: 50px 0;
[1]     at Parser.pp.raise (/home/max/projects/tradeintelclient/node_modules/babylon/index.js:1425:13)
[1]     at Parser.pp.unexpected (/home/max/projects/tradeintelclient/node_modules/babylon/index.js:2907:8)
[1]     at Parser.pp.parseExprAtom (/home/max/projects/tradeintelclient/node_modules/babylon/index.js:754:12)
[1]     at Parser.parseExprAtom (/home/max/projects/tradeintelclient/node_modules/babylon/index.js:4370:22)
[1]     at Parser.pp.parseExprSubscripts (/home/max/projects/tradeintelclient/node_modules/babylon/index.js:509:19)
[1]     at Parser.pp.parseMaybeUnary (/home/max/projects/tradeintelclient/node_modules/babylon/index.js:489:19)
[1]     at Parser.pp.parseExprOps (/home/max/projects/tradeintelclient/node_modules/babylon/index.js:420:19)
[1]     at Parser.pp.parseMaybeConditional (/home/max/projects/tradeintelclient/node_modules/babylon/index.js:402:19)
[1]     at Parser.pp.parseMaybeAssign (/home/max/projects/tradeintelclient/node_modules/babylon/index.js:365:19)
[1]     at Parser.pp.parseExpression (/home/max/projects/tradeintelclient/node_modules/babylon/index.js:329:19)
[1] 
```

**Comment by owenyang0** [comment]
+1 same issue

**Comment by mcpDESIGNS** [comment]
Same issue as well, it's basically just not working / handling .scss files.

    module: {
		loaders: [{
			test: /\.sass$/,
			loader: 'style!css!sass?sourceMap'
                }]
    }

I have all 3 loaders installed as well, and am simply doing a 

    import './header.scss';

**Comment by storrdev** [comment]
I'm having this issue as well. Has anyone found a solution?

FWIW It only happens when I start the server with the sass files imported. If I comment out the import and start the server, I don't get this error. I can then uncomment out the sass imports and everything works like it should.

I'm using babel so I'm wondering if it's a babel issue.

**Comment by bipinshashi** [comment]
+1 @storrdev facing the same issue - works if commenting on server start and then uncommenting after..did you find a solution?

**Comment by storrdev** [comment]
@bipinshashi Adding this code near the top of my webpack config fixed it for me:

`require.extensions['.scss'] = () => {
return;
};
require.extensions['.css'] = () => {
  return;
};`

Hope that helps!

**Comment by rickhanlonii** [comment]
@storrdev that worked for me and so did:

```javascript
import * as styles from './header.scss'
```

**Comment by jhnns** [comment]
@stigmat4j What language is this? Is `:local` legal in Sass?

@storrdev @rickhanlonii @bipinshashi Looks like you were trying to import stylesheets in node. Maybe you're writing an isomorphic app? I would recommend to compile your node app with webpack too (using the [`node` target option](http://webpack.github.io/docs/configuration.html#target))
