### ISSUE TITLE
Error with node-sass-import-once

### ISSUE THREAD

**Issue by webdesserts** [jtangelder/sass-loader#275]
Hello and thanks for your work!
After the latest update(v4.01) I'm getting the following error while trying to use the `node-sass-import-once` importer.

```
Error building modules/Users/mcmullins/dev/apps/veracity/node_modules/node-sass-import-once/index.js:275
  if (!this.options.importOnce) {
           ^

TypeError: Cannot read property 'options' of undefined
    at importer (/Users/mcmullins/dev/apps/veracity/node_modules/node-sass-import-once/index.js:275:12)
    at Object.<anonymous> (/Users/mcmullins/dev/apps/veracity/node_modules/sass-loader/index.js:412:20)
    at options.importer.(anonymous function) (/Users/mcmullins/dev/apps/veracity/node_modules/node-sass/lib/index.js:30
```

It's seems like the importer is expected to be called with some sort of context, but that context is missing? Is this something that's expected with the latest changes?

**Relevant Lines**
https://github.com/at-import/node-sass-import-once/blob/master/index.js#L283
https://github.com/jtangelder/sass-loader/blob/master/index.js#L412

**Comment by webdesserts** [comment]
I'm going to go ahead and close this, thnx for the fix.
