### ISSUE TITLE
upgrading from 4.1.1 to 6.0.0

### ISSUE THREAD

**Issue by Judahmeek** [jtangelder/sass-loader#380]
Hi, @jhnns.

I was wondering if you could help with some `sass-loader` related troubleshooting. I've got errors from three different modules and I've isolated the cause for all the errors to upgrading `sass-loader` from `4.1.1` to `6.0.0`. These errors are all from https://github.com/Judahmeek/bootstrap-loader/tree/update-dependencies/examples/basic and any assistance you (or others) can provide contributes directly towards `bootstrap-loader`'s compatibility with `sass-loader`.

Module 1:
```
ERROR in ./~/extract-text-webpack-plugin/loader.js?{"omit":1,"remove":true}!./~/style-loader!./~/css-loader!./~/resolve-url-loader!./~/sass-loader/lib/loader.js?sourceMap!./~/bootstrap-loader/lib/bootstrap.styles.loader.js?{"bootstrapVersion":3,"preBootstrapCustomizations":"/Users/judahmeek/Apps/bootstrap-loader/examples/basic/app/styles/bootstrap/pre-customizations.scss","bootstrapCustomizations":"/Users/judahmeek/Apps/bootstrap-loader/examples/basic/app/styles/bootstrap/customizations.scss","appStyles":"/Users/judahmeek/Apps/bootstrap-loader/examples/basic/app/styles/app.scss","useCustomIconFontPath":false,"extractStyles":true,"styleLoaders":["style-loader","css-loader","sass-loader"],"styles":["mixins","normalize","print","glyphicons","scaffolding","type","code","grid","tables","forms","buttons","component-animations","dropdowns","button-groups","input-groups","navs","navbar","breadcrumbs","pagination","pager","labels","badges","jumbotron","thumbnails","alerts","progress-bars","media","list-group","panels","wells","responsive-embed","close","modals","tooltip","popovers","carousel","utilities","responsive-utilities"],"scripts":["transition","alert","button","carousel","collapse","dropdown","modal","tooltip","popover","scrollspy","tab","affix"],"configFilePath":"/Users/judahmeek/Apps/bootstrap-loader/examples/basic/.bootstraprc-3-example","bootstrapPath":"/Users/judahmeek/Apps/bootstrap-loader/examples/basic/~/bootstrap-sass","bootstrapRelPath":"../bootstrap-sass"}!./~/bootstrap-loader/no-op.js
Module build failed: Error
    at factoryCallback (/Users/judahmeek/Apps/bootstrap-loader/examples/basic/node_modules/webpack/lib/Compilation.js:259:39)
    at /Users/judahmeek/Apps/bootstrap-loader/examples/basic/node_modules/webpack/lib/NormalModuleFactory.js:234:19
    at onDoneResolving (/Users/judahmeek/Apps/bootstrap-loader/examples/basic/node_modules/webpack/lib/NormalModuleFactory.js:59:20)
    at /Users/judahmeek/Apps/bootstrap-loader/examples/basic/node_modules/webpack/lib/NormalModuleFactory.js:126:20
    at /Users/judahmeek/Apps/bootstrap-loader/examples/basic/node_modules/async/dist/async.js:3694:9
    at /Users/judahmeek/Apps/bootstrap-loader/examples/basic/node_modules/async/dist/async.js:356:16
    at iteratorCallback (/Users/judahmeek/Apps/bootstrap-loader/examples/basic/node_modules/async/dist/async.js:934:13)
    at /Users/judahmeek/Apps/bootstrap-loader/examples/basic/node_modules/async/dist/async.js:840:16
    at /Users/judahmeek/Apps/bootstrap-loader/examples/basic/node_modules/async/dist/async.js:3691:13
    at apply (/Users/judahmeek/Apps/bootstrap-loader/examples/basic/node_modules/async/dist/async.js:21:25)
    at /Users/judahmeek/Apps/bootstrap-loader/examples/basic/node_modules/async/dist/async.js:56:12
    at /Users/judahmeek/Apps/bootstrap-loader/examples/basic/node_modules/webpack/lib/NormalModuleFactory.js:121:22
    at onResolved (/Users/judahmeek/Apps/bootstrap-loader/examples/basic/node_modules/enhanced-resolve/lib/Resolver.js:70:11)
    at loggingCallbackWrapper (/Users/judahmeek/Apps/bootstrap-loader/examples/basic/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at afterInnerCallback (/Users/judahmeek/Apps/bootstrap-loader/examples/basic/node_modules/enhanced-resolve/lib/Resolver.js:138:10)
    at loggingCallbackWrapper (/Users/judahmeek/Apps/bootstrap-loader/examples/basic/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at Resolver.applyPluginsAsyncSeriesBailResult1 (/Users/judahmeek/Apps/bootstrap-loader/examples/basic/node_modules/tapable/lib/Tapable.js:181:46)
    at innerCallback (/Users/judahmeek/Apps/bootstrap-loader/examples/basic/node_modules/enhanced-resolve/lib/Resolver.js:125:19)
    at loggingCallbackWrapper (/Users/judahmeek/Apps/bootstrap-loader/examples/basic/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at /Users/judahmeek/Apps/bootstrap-loader/examples/basic/node_modules/tapable/lib/Tapable.js:283:15
    at /Users/judahmeek/Apps/bootstrap-loader/examples/basic/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:38:4
    at loggingCallbackWrapper (/Users/judahmeek/Apps/bootstrap-loader/examples/basic/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at afterInnerCallback (/Users/judahmeek/Apps/bootstrap-loader/examples/basic/node_modules/enhanced-resolve/lib/Resolver.js:138:10)
    at loggingCallbackWrapper (/Users/judahmeek/Apps/bootstrap-loader/examples/basic/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at Resolver.applyPluginsAsyncSeriesBailResult1 (/Users/judahmeek/Apps/bootstrap-loader/examples/basic/node_modules/tapable/lib/Tapable.js:181:46)
    at innerCallback (/Users/judahmeek/Apps/bootstrap-loader/examples/basic/node_modules/enhanced-resolve/lib/Resolver.js:125:19)
    at loggingCallbackWrapper (/Users/judahmeek/Apps/bootstrap-loader/examples/basic/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at /Users/judahmeek/Apps/bootstrap-loader/examples/basic/node_modules/tapable/lib/Tapable.js:283:15
    at innerCallback (/Users/judahmeek/Apps/bootstrap-loader/examples/basic/node_modules/enhanced-resolve/lib/Resolver.js:123:11)
    at loggingCallbackWrapper (/Users/judahmeek/Apps/bootstrap-loader/examples/basic/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
 @ ./~/bootstrap-loader/lib/bootstrap.loader.js?extractStyles&configFilePath=/Users/judahmeek/Apps/bootstrap-loader/examples/basic/.bootstraprc-3-example!./~/bootstrap-loader/no-op.js 1:21-1696
 @ multi font-awesome-loader bootstrap-loader/lib/bootstrap.loader?extractStyles&configFilePath=/Users/judahmeek/Apps/bootstrap-loader/examples/basic/.bootstraprc-3-example!bootstrap-loader/no-op.js tether ./app/scripts/app

ERROR in ./~/extract-text-webpack-plugin/loader.js?{"omit":1,"remove":true}!./~/style-loader!./~/css-loader!./~/resolve-url-loader!./~/sass-loader/lib/loader.js?sourceMap!./~/bootstrap-loader/lib/bootstrap.styles.loader.js?{"bootstrapVersion":3,"preBootstrapCustomizations":"/Users/judahmeek/Apps/bootstrap-loader/examples/basic/app/styles/bootstrap/pre-customizations.scss","bootstrapCustomizations":"/Users/judahmeek/Apps/bootstrap-loader/examples/basic/app/styles/bootstrap/customizations.scss","appStyles":"/Users/judahmeek/Apps/bootstrap-loader/examples/basic/app/styles/app.scss","useCustomIconFontPath":false,"extractStyles":true,"styleLoaders":["style-loader","css-loader","sass-loader"],"styles":["mixins","normalize","print","glyphicons","scaffolding","type","code","grid","tables","forms","buttons","component-animations","dropdowns","button-groups","input-groups","navs","navbar","breadcrumbs","pagination","pager","labels","badges","jumbotron","thumbnails","alerts","progress-bars","media","list-group","panels","wells","responsive-embed","close","modals","tooltip","popovers","carousel","utilities","responsive-utilities"],"scripts":["transition","alert","button","carousel","collapse","dropdown","modal","tooltip","popover","scrollspy","tab","affix"],"configFilePath":"/Users/judahmeek/Apps/bootstrap-loader/examples/basic/.bootstraprc-3-example","bootstrapPath":"/Users/judahmeek/Apps/bootstrap-loader/examples/basic/~/bootstrap-sass","bootstrapRelPath":"../bootstrap-sass"}!./~/bootstrap-loader/no-op.js
Module build failed: Error
    at factoryCallback (/Users/judahmeek/Apps/bootstrap-loader/examples/basic/node_modules/webpack/lib/Compilation.js:259:39)
    at /Users/judahmeek/Apps/bootstrap-loader/examples/basic/node_modules/webpack/lib/NormalModuleFactory.js:234:19
    at onDoneResolving (/Users/judahmeek/Apps/bootstrap-loader/examples/basic/node_modules/webpack/lib/NormalModuleFactory.js:59:20)
    at /Users/judahmeek/Apps/bootstrap-loader/examples/basic/node_modules/webpack/lib/NormalModuleFactory.js:126:20
    at /Users/judahmeek/Apps/bootstrap-loader/examples/basic/node_modules/async/dist/async.js:3694:9
    at /Users/judahmeek/Apps/bootstrap-loader/examples/basic/node_modules/async/dist/async.js:356:16
    at iteratorCallback (/Users/judahmeek/Apps/bootstrap-loader/examples/basic/node_modules/async/dist/async.js:934:13)
    at /Users/judahmeek/Apps/bootstrap-loader/examples/basic/node_modules/async/dist/async.js:840:16
    at /Users/judahmeek/Apps/bootstrap-loader/examples/basic/node_modules/async/dist/async.js:3691:13
    at apply (/Users/judahmeek/Apps/bootstrap-loader/examples/basic/node_modules/async/dist/async.js:21:25)
    at /Users/judahmeek/Apps/bootstrap-loader/examples/basic/node_modules/async/dist/async.js:56:12
    at /Users/judahmeek/Apps/bootstrap-loader/examples/basic/node_modules/webpack/lib/NormalModuleFactory.js:121:22
    at onResolved (/Users/judahmeek/Apps/bootstrap-loader/examples/basic/node_modules/enhanced-resolve/lib/Resolver.js:70:11)
    at loggingCallbackWrapper (/Users/judahmeek/Apps/bootstrap-loader/examples/basic/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at afterInnerCallback (/Users/judahmeek/Apps/bootstrap-loader/examples/basic/node_modules/enhanced-resolve/lib/Resolver.js:138:10)
    at loggingCallbackWrapper (/Users/judahmeek/Apps/bootstrap-loader/examples/basic/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at Resolver.applyPluginsAsyncSeriesBailResult1 (/Users/judahmeek/Apps/bootstrap-loader/examples/basic/node_modules/tapable/lib/Tapable.js:181:46)
    at innerCallback (/Users/judahmeek/Apps/bootstrap-loader/examples/basic/node_modules/enhanced-resolve/lib/Resolver.js:125:19)
    at loggingCallbackWrapper (/Users/judahmeek/Apps/bootstrap-loader/examples/basic/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at /Users/judahmeek/Apps/bootstrap-loader/examples/basic/node_modules/tapable/lib/Tapable.js:283:15
    at /Users/judahmeek/Apps/bootstrap-loader/examples/basic/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:38:4
    at loggingCallbackWrapper (/Users/judahmeek/Apps/bootstrap-loader/examples/basic/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at afterInnerCallback (/Users/judahmeek/Apps/bootstrap-loader/examples/basic/node_modules/enhanced-resolve/lib/Resolver.js:138:10)
    at loggingCallbackWrapper (/Users/judahmeek/Apps/bootstrap-loader/examples/basic/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at Resolver.applyPluginsAsyncSeriesBailResult1 (/Users/judahmeek/Apps/bootstrap-loader/examples/basic/node_modules/tapable/lib/Tapable.js:181:46)
    at innerCallback (/Users/judahmeek/Apps/bootstrap-loader/examples/basic/node_modules/enhanced-resolve/lib/Resolver.js:125:19)
    at loggingCallbackWrapper (/Users/judahmeek/Apps/bootstrap-loader/examples/basic/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at /Users/judahmeek/Apps/bootstrap-loader/examples/basic/node_modules/tapable/lib/Tapable.js:283:15
    at innerCallback (/Users/judahmeek/Apps/bootstrap-loader/examples/basic/node_modules/enhanced-resolve/lib/Resolver.js:123:11)
    at loggingCallbackWrapper (/Users/judahmeek/Apps/bootstrap-loader/examples/basic/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)

ERROR in /Users/judahmeek/Apps/bootstrap-loader/examples/basic/node_modules/extract-text-webpack-plugin/loader.js?{"omit":1,"remove":true}!/Users/judahmeek/Apps/bootstrap-loader/examples/basic/node_modules/style-loader/index.js!/Users/judahmeek/Apps/bootstrap-loader/examples/basic/node_modules/css-loader/index.js!/Users/judahmeek/Apps/bootstrap-loader/examples/basic/node_modules/resolve-url-loader/index.js!/Users/judahmeek/Apps/bootstrap-loader/examples/basic/node_modules/sass-loader/lib/loader.js?sourceMap!/Users/judahmeek/Apps/bootstrap-loader/examples/basic/node_modules/bootstrap-loader/lib/bootstrap.styles.loader.js?{"bootstrapVersion":3,"preBootstrapCustomizations":"/Users/judahmeek/Apps/bootstrap-loader/examples/basic/app/styles/bootstrap/pre-customizations.scss","bootstrapCustomizations":"/Users/judahmeek/Apps/bootstrap-loader/examples/basic/app/styles/bootstrap/customizations.scss","appStyles":"/Users/judahmeek/Apps/bootstrap-loader/examples/basic/app/styles/app.scss","useCustomIconFontPath":false,"extractStyles":true,"styleLoaders":["style-loader","css-loader","sass-loader"],"styles":["mixins","normalize","print","glyphicons","scaffolding","type","code","grid","tables","forms","buttons","component-animations","dropdowns","button-groups","input-groups","navs","navbar","breadcrumbs","pagination","pager","labels","badges","jumbotron","thumbnails","alerts","progress-bars","media","list-group","panels","wells","responsive-embed","close","modals","tooltip","popovers","carousel","utilities","responsive-utilities"],"scripts":["transition","alert","button","carousel","collapse","dropdown","modal","tooltip","popover","scrollspy","tab","affix"],"configFilePath":"/Users/judahmeek/Apps/bootstrap-loader/examples/basic/.bootstraprc-3-example","bootstrapPath":"/Users/judahmeek/Apps/bootstrap-loader/examples/basic/node_modules/bootstrap-sass","bootstrapRelPath":"../bootstrap-sass"}!/Users/judahmeek/Apps/bootstrap-loader/examples/basic/node_modules/bootstrap-loader/no-op.js doesn't export content
```

Module 2:
```
WARNING in ./~/css-loader!./~/resolve-url-loader!./~/sass-loader/lib/loader.js?sourceMap!./~/bootstrap-loader/lib/bootstrap.styles.loader.js?{"bootstrapVersion":3,"preBootstrapCustomizations":"/Users/judahmeek/Apps/bootstrap-loader/examples/basic/app/styles/bootstrap/pre-customizations.scss","bootstrapCustomizations":"/Users/judahmeek/Apps/bootstrap-loader/examples/basic/app/styles/bootstrap/customizations.scss","appStyles":"/Users/judahmeek/Apps/bootstrap-loader/examples/basic/app/styles/app.scss","useCustomIconFontPath":false,"extractStyles":true,"styleLoaders":["style-loader","css-loader","sass-loader"],"styles":["mixins","normalize","print","glyphicons","scaffolding","type","code","grid","tables","forms","buttons","component-animations","dropdowns","button-groups","input-groups","navs","navbar","breadcrumbs","pagination","pager","labels","badges","jumbotron","thumbnails","alerts","progress-bars","media","list-group","panels","wells","responsive-embed","close","modals","tooltip","popovers","carousel","utilities","responsive-utilities"],"scripts":["transition","alert","button","carousel","collapse","dropdown","modal","tooltip","popover","scrollspy","tab","affix"],"configFilePath":"/Users/judahmeek/Apps/bootstrap-loader/examples/basic/.bootstraprc-3-example","bootstrapPath":"/Users/judahmeek/Apps/bootstrap-loader/examples/basic/~/bootstrap-sass","bootstrapRelPath":"../bootstrap-sass"}!./~/bootstrap-loader/no-op.js
      resolve-url-loader cannot operate: source-map error
      ENOENT: no such file or directory, scandir '/Users/judahmeek/Apps/bootstrap-loader/examples/basic/public/assets'
    
    ERROR in ./~/css-loader!./~/resolve-url-loader!./~/sass-loader/lib/loader.js?sourceMap!./~/bootstrap-loader/lib/bootstrap.styles.loader.js?{"bootstrapVersion":3,"preBootstrapCustomizations":"/Users/judahmeek/Apps/bootstrap-loader/examples/basic/app/styles/bootstrap/pre-customizations.scss","bootstrapCustomizations":"/Users/judahmeek/Apps/bootstrap-loader/examples/basic/app/styles/bootstrap/customizations.scss","appStyles":"/Users/judahmeek/Apps/bootstrap-loader/examples/basic/app/styles/app.scss","useCustomIconFontPath":false,"extractStyles":true,"styleLoaders":["style-loader","css-loader","sass-loader"],"styles":["mixins","normalize","print","glyphicons","scaffolding","type","code","grid","tables","forms","buttons","component-animations","dropdowns","button-groups","input-groups","navs","navbar","breadcrumbs","pagination","pager","labels","badges","jumbotron","thumbnails","alerts","progress-bars","media","list-group","panels","wells","responsive-embed","close","modals","tooltip","popovers","carousel","utilities","responsive-utilities"],"scripts":["transition","alert","button","carousel","collapse","dropdown","modal","tooltip","popover","scrollspy","tab","affix"],"configFilePath":"/Users/judahmeek/Apps/bootstrap-loader/examples/basic/.bootstraprc-3-example","bootstrapPath":"/Users/judahmeek/Apps/bootstrap-loader/examples/basic/~/bootstrap-sass","bootstrapRelPath":"../bootstrap-sass"}!./~/bootstrap-loader/no-op.js
    Module not found: Error: Can't resolve '../fonts/OpenSans-Light.ttf' in '/Users/judahmeek/Apps/bootstrap-loader/examples/basic/node_modules/bootstrap-loader'
     @ ./~/css-loader!./~/resolve-url-loader!./~/sass-loader/lib/loader.js?sourceMap!./~/bootstrap-loader/lib/bootstrap.styles.loader.js?{"bootstrapVersion":3,"preBootstrapCustomizations":"/Users/judahmeek/Apps/bootstrap-loader/examples/basic/app/styles/bootstrap/pre-customizations.scss","bootstrapCustomizations":"/Users/judahmeek/Apps/bootstrap-loader/examples/basic/app/styles/bootstrap/customizations.scss","appStyles":"/Users/judahmeek/Apps/bootstrap-loader/examples/basic/app/styles/app.scss","useCustomIconFontPath":false,"extractStyles":true,"styleLoaders":["style-loader","css-loader","sass-loader"],"styles":["mixins","normalize","print","glyphicons","scaffolding","type","code","grid","tables","forms","buttons","component-animations","dropdowns","button-groups","input-groups","navs","navbar","breadcrumbs","pagination","pager","labels","badges","jumbotron","thumbnails","alerts","progress-bars","media","list-group","panels","wells","responsive-embed","close","modals","tooltip","popovers","carousel","utilities","responsive-utilities"],"scripts":["transition","alert","button","carousel","collapse","dropdown","modal","tooltip","popover","scrollspy","tab","affix"],"configFilePath":"/Users/judahmeek/Apps/bootstrap-loader/examples/basic/.bootstraprc-3-example","bootstrapPath":"/Users/judahmeek/Apps/bootstrap-loader/examples/basic/~/bootstrap-sass","bootstrapRelPath":"../bootstrap-sass"}!./~/bootstrap-loader/no-op.js 6:110-148
```

Module 3:
```
WARNING in ./~/css-loader!./~/resolve-url-loader!./~/sass-loader/lib/loader.js?sourceMap!./~/bootstrap-loader/lib/bootstrap.styles.loader.js?{"bootstrapVersion":3,"preBootstrapCustomizations":"/Users/judahmeek/Apps/bootstrap-loader/examples/basic/app/styles/bootstrap/pre-customizations.scss","bootstrapCustomizations":"/Users/judahmeek/Apps/bootstrap-loader/examples/basic/app/styles/bootstrap/customizations.scss","appStyles":"/Users/judahmeek/Apps/bootstrap-loader/examples/basic/app/styles/app.scss","useCustomIconFontPath":false,"extractStyles":true,"styleLoaders":["style-loader","css-loader","sass-loader"],"styles":["mixins","normalize","print","glyphicons","scaffolding","type","code","grid","tables","forms","buttons","component-animations","dropdowns","button-groups","input-groups","navs","navbar","breadcrumbs","pagination","pager","labels","badges","jumbotron","thumbnails","alerts","progress-bars","media","list-group","panels","wells","responsive-embed","close","modals","tooltip","popovers","carousel","utilities","responsive-utilities"],"scripts":["transition","alert","button","carousel","collapse","dropdown","modal","tooltip","popover","scrollspy","tab","affix"],"configFilePath":"/Users/judahmeek/Apps/bootstrap-loader/examples/basic/.bootstraprc-3-example","bootstrapPath":"/Users/judahmeek/Apps/bootstrap-loader/examples/basic/~/bootstrap-sass","bootstrapRelPath":"../bootstrap-sass"}!./~/bootstrap-loader/no-op.js
      resolve-url-loader cannot operate: source-map error
      ENOENT: no such file or directory, scandir '/Users/judahmeek/Apps/bootstrap-loader/examples/basic/public/assets'
    
    ERROR in ./~/css-loader!./~/resolve-url-loader!./~/sass-loader/lib/loader.js?sourceMap!./~/bootstrap-loader/lib/bootstrap.styles.loader.js?{"bootstrapVersion":3,"preBootstrapCustomizations":"/Users/judahmeek/Apps/bootstrap-loader/examples/basic/app/styles/bootstrap/pre-customizations.scss","bootstrapCustomizations":"/Users/judahmeek/Apps/bootstrap-loader/examples/basic/app/styles/bootstrap/customizations.scss","appStyles":"/Users/judahmeek/Apps/bootstrap-loader/examples/basic/app/styles/app.scss","useCustomIconFontPath":false,"extractStyles":true,"styleLoaders":["style-loader","css-loader","sass-loader"],"styles":["mixins","normalize","print","glyphicons","scaffolding","type","code","grid","tables","forms","buttons","component-animations","dropdowns","button-groups","input-groups","navs","navbar","breadcrumbs","pagination","pager","labels","badges","jumbotron","thumbnails","alerts","progress-bars","media","list-group","panels","wells","responsive-embed","close","modals","tooltip","popovers","carousel","utilities","responsive-utilities"],"scripts":["transition","alert","button","carousel","collapse","dropdown","modal","tooltip","popover","scrollspy","tab","affix"],"configFilePath":"/Users/judahmeek/Apps/bootstrap-loader/examples/basic/.bootstraprc-3-example","bootstrapPath":"/Users/judahmeek/Apps/bootstrap-loader/examples/basic/~/bootstrap-sass","bootstrapRelPath":"../bootstrap-sass"}!./~/bootstrap-loader/no-op.js
    Module not found: Error: Can't resolve '../fonts/OpenSans-Light.ttf' in '/Users/judahmeek/Apps/bootstrap-loader/examples/basic/node_modules/bootstrap-loader'
     @ ./~/css-loader!./~/resolve-url-loader!./~/sass-loader/lib/loader.js?sourceMap!./~/bootstrap-loader/lib/bootstrap.styles.loader.js?{"bootstrapVersion":3,"preBootstrapCustomizations":"/Users/judahmeek/Apps/bootstrap-loader/examples/basic/app/styles/bootstrap/pre-customizations.scss","bootstrapCustomizations":"/Users/judahmeek/Apps/bootstrap-loader/examples/basic/app/styles/bootstrap/customizations.scss","appStyles":"/Users/judahmeek/Apps/bootstrap-loader/examples/basic/app/styles/app.scss","useCustomIconFontPath":false,"extractStyles":true,"styleLoaders":["style-loader","css-loader","sass-loader"],"styles":["mixins","normalize","print","glyphicons","scaffolding","type","code","grid","tables","forms","buttons","component-animations","dropdowns","button-groups","input-groups","navs","navbar","breadcrumbs","pagination","pager","labels","badges","jumbotron","thumbnails","alerts","progress-bars","media","list-group","panels","wells","responsive-embed","close","modals","tooltip","popovers","carousel","utilities","responsive-utilities"],"scripts":["transition","alert","button","carousel","collapse","dropdown","modal","tooltip","popover","scrollspy","tab","affix"],"configFilePath":"/Users/judahmeek/Apps/bootstrap-loader/examples/basic/.bootstraprc-3-example","bootstrapPath":"/Users/judahmeek/Apps/bootstrap-loader/examples/basic/~/bootstrap-sass","bootstrapRelPath":"../bootstrap-sass"}!./~/bootstrap-loader/no-op.js 6:110-148
```

**Comment by Judahmeek** [comment]
Completely and utterly solved by https://github.com/bholloway/resolve-url-loader/pull/45. I'm rather blown away. :D

**Comment by jhnns** [comment]
That is hell of a stack trace! :)
